// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID             string `json:"id"`
	DocumentNumber int    `json:"document_number"`
}

type NewAccount struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewTransaction struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type OperationsType struct {
	ID          string  `json:"id"`
	Description string  `json:"description"`
	Account     float64 `json:"account"`
	EventDate   string  `json:"eventDate"`
}

type Transaction struct {
	ID             string          `json:"id"`
	Account        *Account        `json:"account"`
	OperationsType *OperationsType `json:"operationsType"`
}
