// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID             string `json:"id"`
	DocumentNumber int    `json:"documentNumber"`
}

type NewAccount struct {
	DocumentNumber int `json:"documentNumber"`
}

type OperationsType struct {
	ID          string `json:"id"`
	Description string `json:"description"`
}

type Transaction struct {
	ID               string          `json:"id"`
	AccountID        int             `json:"accountId"`
	OperationsTypeID int             `json:"operationsTypeId"`
	Amount           float64         `json:"amount"`
	EventDate        string          `json:"eventDate"`
	Account          *Account        `json:"account"`
	OperationsType   *OperationsType `json:"operationsType"`
}
