version: "3.5"
services: 
  service-labbankgo-api:
    container_name: "labbankgo-api"
    image: "ruyjfs/go"
    build: docker/.
    working_dir: /app
    volumes:
      - .:/app
    # command: sh -c '~/go/bin/gin'
    command: sh -c 'go run main.go'
    ports:
      - "8080:8080"
    restart: always
    tty: true
    # links:
    #   - service-labbankgo-db
    # depends_on:
    #   - service-labbankgo-db

  # service-labbankgo-db:
  #   image: postgres:alpine
  #   container_name: labbankgo-db
  #   environment:
  #     POSTGRES_DB: labbankgo-db
  #     POSTGRES_USER: labbankgo-usr
  #     POSTGRES_PASSWORD: labbankgo-psw
  #   ports:
  #     - 5432:5432
  #   tty: true
  #   restart: always

  # db-service:
  #   # healthcheck:
  #   #   test: ['CMD-SHELL', 'pg_isready -U usr_sli -d usr_sli || exit 1']
  #   #   interval: 10s
  #   #   timeout: 5s
  #   #   retries: 3
  #   image: postgres:11.5-alpine
  #   container_name: sli-db
  #   environment:
  #     - POSTGRES_DB=db_sli
  #     - POSTGRES_USER=usr_sli
  #     - POSTGRES_PASSWORD=psw_sli
  #     - POSTGRES_DB_TEST=db_sli_test
  #   ports:
  #     - 5401:5432
  #   expose:
  #     - 5432
  #   volumes:
  #     - ./database/docker-data/postgres:/var/lib/postgresql/data
  #     - ./database/scripts:/docker-entrypoint-initdb.d