version: "3.5"
services: 
  labbankgo-api-service:
    container_name: "labbankgo-api"
    image: "ruyjfs/go"
    build: docker/.
    working_dir: /app
    volumes:
      - .:/app
    env_file: ./docker/local.env
    entrypoint: ["sh", "./docker/entrypoint.sh"]
    command: sh -c 'gin --port=8080'
    ports:
      - "8085:8080"
    restart: always
    tty: true
    links:
      - labbankgo-db-service
    depends_on:
      - labbankgo-db-service
  labbankgo-db-service:
    container_name: labbankgo-db
    image: postgres:alpine
    env_file: ./docker/local.env
    volumes:
      - ./docker/database/postgres/data:/var/lib/postgresql/data
      - ./docker/database/postgres/scripts:/docker-entrypoint-initdb.d
    tty: true
    restart: always
    healthcheck:
      #IMPORTANT! change this if you have changed a local.env
      test: ["CMD-SHELL", "pg_isready -U labbankgo-usr -d labbankgo-db"]
      interval: 10s
      timeout: 5s
      retries: 5
  labbankgo-adminer-service:
    container_name: labbankgo-adminer
    image: adminer
    restart: always
    ports:
      - 8086:8080
    env_file: ./docker/local.env
    links:
      - labbankgo-db-service
    depends_on:
      - labbankgo-db-service